# Generated by Django 3.0.6 on 2020-05-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Smeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rektorfio', models.CharField(max_length=100)),
                ('table_smetastudenta', models.CharField(max_length=100)),
                ('table_spisokdolznostnixsmeta', models.CharField(max_length=100)),
                ('kol_chel', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SluzhebnajaZapiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podrazdelenie', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prikaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stringprikaz', models.CharField(max_length=100)),
                ('preambula', models.CharField(max_length=100)),
                ('glavbyxfio', models.CharField(max_length=100)),
                ('table_spisokdolznostnixprikaz', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtchetStudenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fioshort', models.CharField(max_length=100)),
                ('this_start', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NapravlenieStudenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ys', models.DateField()),
                ('iofglavnyi_st', models.CharField(max_length=100)),
                ('yf', models.DateField()),
                ('fiofull', models.CharField(max_length=100)),
                ('ds', models.DateField()),
                ('dolzn_podrazd_st', models.CharField(max_length=100)),
                ('mf', models.DateField()),
                ('df', models.DateField()),
                ('gruppa', models.CharField(max_length=100)),
                ('ms', models.DateField()),
                ('cel_poezdki', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto_naznacheniya', models.CharField(blank=True, max_length=100)),
                ('naselennyj_punkt', models.CharField(blank=True, max_length=100)),
                ('nazvanie_meropriyatie', models.CharField(blank=True, max_length=100)),
                ('daystart', models.DateField(blank=True)),
                ('dayend', models.DateField(blank=True)),
                ('forma_obucheniya', models.CharField(blank=True, max_length=100)),
                ('osnova_obucheniya', models.CharField(blank=True, max_length=100)),
                ('table_spisokstudentov', models.CharField(blank=True, max_length=100)),
                ('kompensaciya', models.CharField(blank=True, max_length=100)),
                ('iofrektor', models.CharField(blank=True, max_length=100)),
                ('dolzn_podrazd', models.CharField(blank=True, max_length=100)),
                ('iofglavnyi', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
