# Generated by Django 3.0.6 on 2020-05-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common',
            name='dayend',
        ),
        migrations.RemoveField(
            model_name='common',
            name='daystart',
        ),
        migrations.RemoveField(
            model_name='common',
            name='dolzn_podrazd',
        ),
        migrations.RemoveField(
            model_name='common',
            name='ioFglavnyi',
        ),
        migrations.RemoveField(
            model_name='common',
            name='nazvanie_meropriyatie',
        ),
        migrations.RemoveField(
            model_name='dva',
            name='kol_chel',
        ),
        migrations.RemoveField(
            model_name='dva',
            name='rektorFio',
        ),
        migrations.RemoveField(
            model_name='dva',
            name='table_smetaStudenta',
        ),
        migrations.RemoveField(
            model_name='dva',
            name='table_spisokDolznostnixSmeta',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='forma_obucheniya',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='glavbyxFio',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='ioFrektor',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='kompensaciya',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='mesto_naznacheniya',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='osnova_obucheniya',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='preambula',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='stringPrikaz',
        ),
        migrations.RemoveField(
            model_name='odin',
            name='table_spisokStudentov',
        ),
    ]
