# Generated by Django 3.0.6 on 2020-05-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='cel_poezdki',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='df',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='dolzn_podrazd_st',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='ds',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='fiofull',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='gruppa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='iofglavnyi_st',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='mf',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='ms',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='yf',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='ys',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='otchetstudenta',
            name='fioshort',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='otchetstudenta',
            name='this_start',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='glavbyxfio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='preambula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='stringprikaz',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prikaz',
            name='table_spisokdolznostnixprikaz',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sluzhebnajazapiska',
            name='podrazdelenie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='kol_chel',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='rektorfio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='table_smetastudenta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='table_spisokdolznostnixsmeta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
