# Generated by Django 3.0.6 on 2020-05-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200521_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osnovnye',
            name='dayend',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='daystart',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='dolzn_podrazd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='forma_obucheniya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='iofglavnyi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='iofrektor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='kompensaciya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='mesto_naznacheniya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='naselennyj_punkt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='nazvanie_meropriyatie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='osnova_obucheniya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='table_spisokstudentov',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
