# Generated by Django 3.0.6 on 2020-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200524_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='df',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='ds',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='mf',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='ms',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='yf',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='napravleniestudenta',
            name='ys',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='dayend',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='osnovnye',
            name='daystart',
            field=models.DateField(blank=True),
        ),
    ]
