# Generated by Django 3.0.6 on 2020-05-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_meropriyatie', models.CharField(max_length=200)),
                ('daystart', models.CharField(max_length=200)),
                ('dayend', models.CharField(max_length=200)),
                ('dolzn_podrazd', models.CharField(max_length=200)),
                ('ioFglavnyi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='dva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_spisokDolznostnixSmeta', models.CharField(max_length=200)),
                ('kol_chel', models.CharField(max_length=200)),
                ('table_smetaStudenta', models.CharField(max_length=200)),
                ('rektorFio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='odin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osnova_obucheniya', models.CharField(max_length=200)),
                ('ioFrektor', models.CharField(max_length=200)),
                ('table_spisokStudentov', models.CharField(max_length=200)),
                ('preambula', models.CharField(max_length=200)),
                ('forma_obucheniya', models.CharField(max_length=200)),
                ('kompensaciya', models.CharField(max_length=200)),
                ('glavbyxFio', models.CharField(max_length=200)),
                ('stringPrikaz', models.CharField(max_length=200)),
                ('mesto_naznacheniya', models.CharField(max_length=200)),
            ],
        ),
    ]
